# Generated by Django 3.1 on 2020-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_auto_20200902_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default='', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timer',
            field=models.SmallIntegerField(default=5, verbose_name='Отсрочка отправки'),
        ),
    ]
