# Generated by Django 3.1 on 2020-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_auto_20200903_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Кому отправляем'),
        ),
    ]
